import type { NextPage } from 'next';
import Head from 'next/head';

const Home: React.FC<NextPage> = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main></main>
      <footer></footer>
    </div>
  );
};

export default Home;
